---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: dev-toolkit
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/VLXMDE/dev-toolkit
